import '../../styles/globals.css';



export const metadata = {
  title: 'Shita-Kiri-Suzume Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/favicon.ico'/>
      </head>
      <body className="max-w-7xl mx-auto">
        {children}
        </body>
    </html>
  )
}
